name: lightgbm-gift
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - mlflow>=1.6.0
      - matplotlib==3.5.2
      - mlflow==1.26.1
      - pandas==1.3.4
      - numpy==1.22
